version: '3.8'

services:
  web:
    build: .
    container_name: paragourmet_web
    command: gunicorn paragourmet.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - db_data:/app/db_data         # SQLite 파일 경로가 /app/db_data/db.sqlite3 면 좋음
      - static_volume:/app/staticfiles

    # 나중에 Postgres 붙일 때 예시 (헬스체크 필수)
    # depends_on:
    #   db:
    #     condition: service_healthy

volumes:
  db_data:
  static_volume:
