services:
  web:
    build: .
    container_name: paragourmet_web
    # PATH 이슈 회피를 원하면 아래처럼:
    command: python -m gunicorn paragourmet.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - db_data:/app/db_data
      - static_volume:/app/staticfiles

volumes:
  db_data:
  static_volume:
