# .github/workflows/deploy.yml

name: Deploy to Server (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted # Use self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create .env file on runner
      run: |
        echo "${{ secrets.APP_ENV_VARS }}" > .env

    - name: Build and run Docker Compose
      run: |
        docker compose build
        docker compose up -d --remove-orphans
        docker compose exec web python manage.py migrate --noinput
        docker compose exec web python manage.py collectstatic --noinput
