name: Deploy to Server (Self-Hosted)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    timeout-minutes: 30
    concurrency:
      group: deploy-prod
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file on runner
        run: |
          printf "%s" "${{ secrets.APP_ENV_VARS }}" > .env
          ls -l .env
          head -n 5 .env || true

      - name: Validate Compose config
        run: docker compose config

      - name: Build images
        run: docker compose build --progress=plain

      - name: Verify gunicorn installed
        run: docker compose run --rm web python -m gunicorn --version

      - name: Django migrate (one-off)
        run: docker compose run --rm web python manage.py migrate --noinput

      - name: Django collectstatic (one-off)
        run: docker compose run --rm web python manage.py collectstatic --noinput

      - name: Up services
        run: docker compose up -d --remove-orphans --wait

      - name: Smoke test
        run: |
          sleep 3
          curl -fsS http://localhost:8000/ || (docker compose logs --no-color web && exit 1)
