# .github/workflows/deploy.yml

name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/paragourmet:latest

    - name: Deploy to remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script:
          # Navigate to your application directory on the server
          - cd /path/to/your/app/directory # IMPORTANT: Change this to your actual path
          # Pull the latest image
          - docker compose pull
          # Stop and remove old containers, then start new ones
          - docker compose up -d --remove-orphans
          # Run Django migrations (if any)
          - docker compose exec web python manage.py migrate --noinput
          # Collect static files (if any changes)
          - docker compose exec web python manage.py collectstatic --noinput

    - name: Clean up Docker images (optional)
      if: always()
      run: docker rmi $(docker images -f "dangling=true" -q) || true
